# Generated by Django 4.1 on 2024-10-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_editproduct_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editProduct',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='delete_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
