# Generated by Django 4.2.15 on 2024-10-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_worksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='worksite_picture',
            field=models.ImageField(blank=True, null=True, upload_to='worksite_pics/'),
        ),
        migrations.CreateModel(
            name='WorksiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worksite_images/')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='djangoapp.worksite')),
            ],
        ),
    ]
