# Generated by Django 4.1 on 2024-10-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
